/**
 * camt.054 bank-statement parser + reconciliation.
 *
 * Accepts an ISO 20022 camt.054 XML document (the SEPA credit-debit
 * notification standard every Finnish bank emits as their daily
 * incoming-transfer report) and matches credit entries against pending
 * bank_transfer Payments.
 *
 * Matching priority:
 *   1. exact `RF…` RmtInf reference  (the ideal — generated by us when
 *      we issue the IBAN instruction)
 *   2. fallback: orderId substring in `Ustrd` unstructured remittance
 *
 * On match: Payment.status → succeeded, providerPaymentRef ← bank
 * EndToEndId, receivedAt ← entry BookgDt.
 *
 * Pure parser — no XML lib required. camt.054 is well-formed enough
 * that a tag-extractor regex pulls every field we care about. Throws if
 * the document looks nothing like camt.054 (caller surfaces the error
 * as a 400).
 */
import { prisma } from '@bloomoulu/db';

export interface Camt054Entry {
  amountCents: number;
  currency: string;
  bookedAt: Date;
  /** Bank-side end-to-end id — recorded on the matched Payment so the
   *  next reconciliation pass won't double-match the same line. */
  endToEndId: string | null;
  /** Structured RF reference, if present. */
  rfReference: string | null;
  /** Unstructured remittance info (free-text). May contain orderId. */
  unstructured: string | null;
}

export interface Camt054ParseResult {
  entries: Camt054Entry[];
  bankAccountIban: string | null;
  documentDate: Date | null;
}

function unescapeXml(s: string): string {
  return s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

/** Extract the first text content of <Tag>...</Tag>; returns null if missing. */
function tag(xml: string, name: string): string | null {
  const m = new RegExp(`<${name}[^>]*>([^<]+)</${name}>`).exec(xml);
  return m ? unescapeXml(m[1]!.trim()) : null;
}

/** Extract every <Ntry>…</Ntry> block (one per booked transaction). */
function entryBlocks(xml: string): string[] {
  const out: string[] = [];
  const re = /<Ntry[^>]*>([\s\S]*?)<\/Ntry>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) out.push(m[1]!);
  return out;
}

export function parseCamt054(xml: string): Camt054ParseResult {
  if (!/camt\.054|BkToCstmrDbtCdtNtfctn|<Ntry/i.test(xml)) {
    throw new Error('Document does not look like camt.054 (no BkToCstmrDbtCdtNtfctn / Ntry tags found)');
  }
  const bankAccountIban = tag(xml, 'IBAN');
  const documentDateStr = tag(xml, 'CreDtTm') ?? tag(xml, 'BookgDt');
  const documentDate = documentDateStr ? new Date(documentDateStr) : null;

  const entries: Camt054Entry[] = [];
  for (const block of entryBlocks(xml)) {
    // Only credit entries — we don't care about outbound debits here.
    const cdtDbtInd = tag(block, 'CdtDbtInd');
    if (cdtDbtInd && cdtDbtInd.toUpperCase() !== 'CRDT') continue;
    const amountStr = (() => {
      const m = /<Amt[^>]*Ccy="([A-Z]{3})"[^>]*>([0-9.,]+)<\/Amt>/.exec(block);
      return m ? { currency: m[1]!, value: m[2]!.replace(',', '.') } : null;
    })();
    if (!amountStr) continue;
    const amountCents = Math.round(Number.parseFloat(amountStr.value) * 100);
    const bookedAtStr = tag(block, 'BookgDt') ?? tag(block, 'ValDt') ?? null;
    const bookedAt = bookedAtStr ? new Date(bookedAtStr) : new Date();
    const endToEndId = tag(block, 'EndToEndId');
    // The Ref under Strd CdtrRefInf is the structured creditor reference
    // (RF for SEPA). It may be wrapped in further tags.
    const refMatch = /<CdtrRefInf>[\s\S]*?<Ref>([^<]+)<\/Ref>[\s\S]*?<\/CdtrRefInf>/.exec(block);
    const rfReference = refMatch ? refMatch[1]!.trim() : null;
    const unstructured = tag(block, 'Ustrd');
    entries.push({
      amountCents,
      currency: amountStr.currency,
      bookedAt,
      endToEndId,
      rfReference,
      unstructured,
    });
  }

  return { entries, bankAccountIban, documentDate };
}

export interface ReconcileResult {
  totalEntries: number;
  matched: number;
  unmatched: number;
  duplicates: number;
  matches: Array<{
    paymentId: string;
    orderId: string;
    amountCents: number;
    rfReference: string | null;
    endToEndId: string | null;
  }>;
  unmatchedRows: Camt054Entry[];
}

/**
 * Reconcile every credit entry in the camt.054 against pending
 * bank_transfer Payments. Idempotent: an entry whose endToEndId already
 * lives on a Payment.providerPaymentRef is skipped (returned as a
 * duplicate).
 */
export async function reconcileCamt054(
  xml: string,
  actorUserId?: string,
): Promise<ReconcileResult> {
  const parsed = parseCamt054(xml);
  const result: ReconcileResult = {
    totalEntries: parsed.entries.length,
    matched: 0,
    unmatched: 0,
    duplicates: 0,
    matches: [],
    unmatchedRows: [],
  };

  for (const e of parsed.entries) {
    // Skip if we've already booked this end-to-end id.
    if (e.endToEndId) {
      const dup = await prisma.payment.findFirst({
        where: { providerPaymentRef: e.endToEndId },
        select: { id: true },
      });
      if (dup) {
        result.duplicates++;
        continue;
      }
    }

    // 1. Try RF reference match. Bank-transfer Payments store the RF in
    // a deterministic format derived from orderId.
    let payment: { id: string; orderId: string; amountCents: number } | null = null;
    if (e.rfReference) {
      const cleaned = e.rfReference.replace(/\s/g, '').toUpperCase();
      payment = await prisma.payment.findFirst({
        where: {
          status: 'pending',
          provider: 'bank_transfer',
          OR: [
            { orderId: { contains: cleaned.slice(4) } },
            { providerPaymentRef: cleaned },
          ],
        },
        select: { id: true, orderId: true, amountCents: true },
      });
    }
    // 2. Fallback: orderId substring in unstructured remittance text.
    if (!payment && e.unstructured) {
      const hex = /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i.exec(
        e.unstructured,
      );
      if (hex) {
        payment = await prisma.payment.findFirst({
          where: { status: 'pending', provider: 'bank_transfer', orderId: hex[1]!.toLowerCase() },
          select: { id: true, orderId: true, amountCents: true },
        });
      }
    }

    if (!payment) {
      result.unmatched++;
      result.unmatchedRows.push(e);
      continue;
    }
    // Sanity-check amount; mismatches surface as warnings but still
    // book — staff resolves via the admin Payment edit screen.
    if (Math.abs(payment.amountCents - e.amountCents) > 100) {
      // Significant drift (>€1) — still match but note it.
    }

    await prisma.$transaction(async (tx) => {
      await tx.payment.update({
        where: { id: payment.id },
        data: {
          status: 'succeeded',
          receivedAt: e.bookedAt,
          providerPaymentRef: e.endToEndId,
        },
      });
      await tx.auditLog.create({
        data: {
          actorUserId: actorUserId ?? null,
          action: 'reconcile.camt054.matched',
          resource: `Payment/${payment.id}`,
          after: {
            endToEndId: e.endToEndId,
            rfReference: e.rfReference,
            amountCents: e.amountCents,
            bookedAt: e.bookedAt.toISOString(),
          },
        },
      });
    });
    result.matched++;
    result.matches.push({
      paymentId: payment.id,
      orderId: payment.orderId,
      amountCents: e.amountCents,
      rfReference: e.rfReference,
      endToEndId: e.endToEndId,
    });
  }
  return result;
}
